In [17]:
import csv
import pandas as pd

In [18]:
reddit_questions = pd.read_csv('data/reddit/reddit_questions.csv', on_bad_lines='skip',  sep = ';')
reddit_answers = pd.read_csv('data/reddit/reddit_answers.csv', on_bad_lines='skip',  sep = ';')

In [19]:
reddit_questions.head()

,id,text,votes,timestamp,datetime
0,izucgz,What's the purpose of life?,8,1.601076e+09,Fri Sep 25 23:13:31 2020 UTC
1,9c784/,"I've tried to quit smoking, this is my seventh...",11,1.250712e+09,Wed Aug 19 19:58:54 2009 UTC
2,iylxwl,"For those who have a slave master last name, w...",0,1.600904e+09,Wed Sep 23 23:35:15 2020 UTC
3,gmmlj4,How do you think humans will become extinct?,21998,1.589887e+09,Tue May 19 11:18:05 2020 UTC
4,ishb7v,What is a movie So Disturbing you couldn't be ...,13,1.600074e+09,Mon Sep 14 08:53:53 2020 UTC

In [20]:
reddit_answers.head()

,Unnamed: 0,q_id,text,votes
0,0,hvbvpz,Two pet ducks. You may be tempted to go for on...,2359.0
1,1,hvbvpz,Nice try Jeff Bezos,764.0
2,2,hvbvpz,A curved shower rod. Seriously. $10 for a tens...,1525.0
3,3,hvbvpz,Another monitor. Your productivity will increa...,1227.0
4,4,hvbvpz,A nasal irrigation kit - either the electronic...,659.0

In [25]:
def insertRedditData(writer):
    for index, row in reddit_questions.iterrows():
        #Get the answers for the question
        r_answers = reddit_answers.loc[reddit_answers['q_id'] == row['id']]

        #Remove the invalid answers
        r_answers = r_answers.drop(r_answers[r_answers.text.str.len() < 15].index)

        #Get the best voted
        r_answers = r_answers[r_answers['votes'] > r_answers.loc[:, 'votes'].mean()]

        for i, r in r_answers.iterrows(): 
            writer.writerow([row['text'], r['text']])
        
def insertInteractionsData(writer):
    filename = 'data/interactions.csv'

    with open(filename, 'r') as interactionsfile:
        datareader = csv.reader(interactionsfile)
        for row in datareader:
            writer.writerow([row[0], row[1]])

In [ ]:
csvfile = open('data/dataset.csv', 'w')
writer = csv.writer(csvfile)
writer.writerow(['question', 'answer'])

insertInteractionsData(writer)
insertRedditData(writer)

csvfile.close()